// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialHX.Data;

#nullable disable

namespace SocialHX.Migrations
{
    [DbContext(typeof(SocialHXContext))]
    partial class SocialHXContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SocialHX.Models.Activity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ActivityID");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("SocialHX.Models.FollowUpWeek1", b =>
                {
                    b.Property<int>("FollowUpWeek1ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrescriptionID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Response")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentAdjustments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentReport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FollowUpWeek1ID");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("FollowUpWeek1");
                });

            modelBuilder.Entity("SocialHX.Models.FollowUpWeek4", b =>
                {
                    b.Property<int>("FollowUpWeek4ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barriers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DidAttend")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DidMeet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventsAttended")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Feelings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrescriptionID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Refill")
                        .HasColumnType("INTEGER");

                    b.HasKey("FollowUpWeek4ID");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("FollowUpWeek4");
                });

            modelBuilder.Entity("SocialHX.Models.Prescriber", b =>
                {
                    b.Property<int>("PrescriberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PrescriberID");

                    b.ToTable("Prescriber");
                });

            modelBuilder.Entity("SocialHX.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Event1ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Event1Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Event1OtherPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Event2ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Event2Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Event2OtherPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Event3ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Event3Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Event3OtherPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Event4ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Event4Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Event4OtherPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrescriberID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrescriptionID");

                    b.HasIndex("Event1ID");

                    b.HasIndex("Event2ID");

                    b.HasIndex("Event3ID");

                    b.HasIndex("Event4ID");

                    b.HasIndex("PrescriberID");

                    b.HasIndex("StudentID");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("SocialHX.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("SocialHX.Models.FollowUpWeek1", b =>
                {
                    b.HasOne("SocialHX.Models.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("SocialHX.Models.FollowUpWeek4", b =>
                {
                    b.HasOne("SocialHX.Models.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("SocialHX.Models.Prescription", b =>
                {
                    b.HasOne("SocialHX.Models.Activity", "Event1")
                        .WithMany()
                        .HasForeignKey("Event1ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialHX.Models.Activity", "Event2")
                        .WithMany()
                        .HasForeignKey("Event2ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialHX.Models.Activity", "Event3")
                        .WithMany()
                        .HasForeignKey("Event3ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialHX.Models.Activity", "Event4")
                        .WithMany()
                        .HasForeignKey("Event4ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialHX.Models.Prescriber", "Prescriber")
                        .WithMany()
                        .HasForeignKey("PrescriberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialHX.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event1");

                    b.Navigation("Event2");

                    b.Navigation("Event3");

                    b.Navigation("Event4");

                    b.Navigation("Prescriber");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
